#!/bin/bash

watchexec --project-origin \
  /Users/alan/workshop/alanwsmith.com\
  --debounce 1sec \
  --watch \
  /Users/alan/workshop/alanwsmith.com/templates \
  --watch \
  /Users/alan/workshop/alanwsmith.com/content \
  -e neo,j2 cargo run --bin neo

